# 🐍 Python for AI/ML: NumPy, Pandas, Matplotlib, Scikit-learn

Welcome! In this notebook, you'll learn how to use Python libraries essential for AI and ML. These include:

- **NumPy** for numerical operations
- **Pandas** for data analysis
- **Matplotlib** for data visualization
- **Scikit-learn** for basic machine learning

No prior programming experience is needed — let's start!

## 🧠 1. NumPy Basics
NumPy lets us work with arrays and do mathematical operations efficiently.

In [1]:
import numpy as np

# Creating arrays
a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])
print("1D Array:", a)
print("2D Array:", b)
print("Shape of a:", a.shape)
print("Shape of b:", b.shape)

1D Array: [1 2 3]
2D Array: [[1 2]
 [3 4]]
Shape of a: (3,)
Shape of b: (2, 2)


In [2]:
# Array math
print("a + 10:", a + 10)
print("a * 2:", a * 2)
print("Sum of b:", b.sum())
print("Mean of b:", b.mean())

a + 10: [11 12 13]
a * 2: [2 4 6]
Sum of b: 10
Mean of b: 2.5


In [3]:
# Special arrays
print("Zeros:", np.zeros((2,3)))
print("Ones:", np.ones((2,3)))
print("Range:", np.arange(0, 10, 2))
print("Random:", np.random.randint(1, 10, size=(2,3)))

Zeros: [[0. 0. 0.]
 [0. 0. 0.]]
Ones: [[1. 1. 1.]
 [1. 1. 1.]]
Range: [0 2 4 6 8]
Random: [[7 9 1]
 [5 4 1]]


## 📊 2. Pandas Basics
Pandas helps us work with tables (like spreadsheets).

In [ ]:
import pandas as pd

# Creating a DataFrame
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [16, 17, 16],
    "Score": [85, 92, 78]
}
df = pd.DataFrame(data)
print(df)

In [ ]:
# Exploring the data
print(df.head())
print(df.describe())
print(df.info())

In [ ]:
# Filtering data
print(df[df["Score"] > 80])
print(df[df["Age"] == 16])

In [ ]:
# Grouping and sorting
print(df.groupby("Age")["Score"].mean())
print(df.sort_values("Score", ascending=False))

## 📈 3. Matplotlib Basics
Matplotlib helps us draw charts and visualize data.

In [ ]:
import matplotlib.pyplot as plt

# Line plot
x = [1, 2, 3, 4]
y = [10, 20, 25, 30]
plt.plot(x, y)
plt.title("Line Plot Example")
plt.xlabel("X Axis")
plt.ylabel("Y Axis")
plt.show()

In [ ]:
# Bar chart
plt.bar(df["Name"], df["Score"])
plt.title("Student Scores")
plt.xlabel("Name")
plt.ylabel("Score")
plt.show()

In [ ]:
# Scatter plot
plt.scatter(df["Age"], df["Score"], color='red')
plt.title("Age vs Score")
plt.xlabel("Age")
plt.ylabel("Score")
plt.show()

In [ ]:
# Histogram
plt.hist(df["Score"], bins=5)
plt.title("Score Distribution")
plt.xlabel("Score")
plt.ylabel("Frequency")
plt.show()

## 🤖 4. Scikit-learn Basics
Scikit-learn is a machine learning library. Let's try a simple linear regression model.

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

X = np.array([[1], [2], [3], [4], [5]])
y = np.array([1.2, 1.9, 3.2, 3.8, 5.1])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

model = LinearRegression()
model.fit(X_train, y_train)

print("Slope:", model.coef_)
print("Intercept:", model.intercept_)
print("Prediction for 6:", model.predict([[6]]))

## 🧠 5. Mini Project: Iris Dataset
We'll analyze the famous Iris flower dataset.

In [ ]:
iris = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv")
print(iris.head())
print(iris.describe())

In [ ]:
# Plotting
plt.scatter(iris["sepal_length"], iris["sepal_width"], c=iris["species"].astype("category").cat.codes)
plt.title("Sepal Length vs Width")
plt.xlabel("Sepal Length")
plt.ylabel("Sepal Width")
plt.show()

In [ ]:
# Training a classifier
from sklearn.neighbors import KNeighborsClassifier

X = iris.drop("species", axis=1)
y = iris["species"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
print("Accuracy:", knn.score(X_test, y_test))

## ✅ Summary & Next Steps
In this notebook, you learned:
- NumPy: Arrays, math, reshaping
- Pandas: DataFrames, filtering, grouping
- Matplotlib: Line, bar, scatter, histogram
- Scikit-learn: Linear Regression and Classification

🎓 You're ready to explore more with Seaborn, TensorFlow, or build your own AI project!